#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides: solr
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Controls Solr-exporter as a Service
### END INIT INFO

# Set the default variable values
test "$SOLR_INSTALL_DIR" == "" && SOLR_INSTALL_DIR="/opt/solr"
test "$SOLR_EXPORTER_INSTALL_DIR" == "" && SOLR_EXPORTER_INSTALL_DIR="$SOLR_INSTALL_DIR/contrib/prometheus-exporter"
test "$SOLR_EXPORTER_SOLR_URL" == "" && SOLR_EXPORTER_SOLR_URL="http://localhost:8983/solr"
test "$SOLR_EXPORTER_CONFIG_DIR" == "" && SOLR_EXPORTER_CONFIG_DIR="conf/solr-exporter-config.xml"
test "$SOLR_EXPORTER_LOG_FILE" == "" && SOLR_EXPORTER_LOG_FILE=/dev/null
test "$SOLR_EXPORTER_NUM_THREADS" == "" && SOLR_EXPORTER_NUM_THREADS="1"
test "$SOLR_EXPORTER_PORT" == "" && SOLR_EXPORTER_PORT=9854
test "$SOLR_EXPORTER_CMD" == "" && SOLR_EXPORTER_CMD="-p $SOLR_EXPORTER_PORT -b $SOLR_EXPORTER_SOLR_URL -f $SOLR_EXPORTER_INSTALL_DIR/$SOLR_EXPORTER_CONFIG_DIR -n $SOLR_EXPORTER_NUM_THREADS"

# Check whether solr-exporter exists
if [ ! -d "$SOLR_EXPORTER_INSTALL_DIR" ]; then
  echo "$SOLR_EXPORTER_INSTALL_DIR not found! Please check the SOLR_EXPORTER_INSTALL_DIR setting in your $0 script."
  exit 1
fi

# Specify the user to run solr-exporter as
RUNAS="solr"

# Check whether the specified RUNAS user exists
runas_uid="`id -u "$RUNAS"`"
if [ $? -ne 0 ]; then
  echo "User $RUNAS not found! Please create the $RUNAS user before running this script."
  exit 1
fi

# Check whether the action requested is valid
case "$1" in
  start|stop|status|restart)
    SERVICE_CMD="$1"
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
    exit
esac

function start {
    if [ -z "$PID" ]; then
        su -c "nohup $SOLR_EXPORTER_INSTALL_DIR/bin/solr-exporter $SOLR_EXPORTER_CMD </dev/null >$SOLR_EXPORTER_LOG_FILE 2>&1 &" - "$RUNAS"
        echo "Solr-exporter started"
    fi
}

function stop {
    if [ -n "$PID" ]; then 
        echo "Stopping solr-exporter $PID"; 
        kill $PID; 
        while [ -n "$PID" ]; do 
            set_pid; 
            sleep 1
        done
        echo "Solr-exporter stopped"; 
    fi
}

function set_pid {
    PID=$(ps -elf |grep \\-Dapp.name=solr-exporter |grep -P "(?<=-p )$SOLR_EXPORTER_PORT" |grep -P -o '(?<=-Dapp.pid=)[0-9]+')
}

function status {
    if [ -z "$PID" ]; then echo "No solr-exporter running"; else echo "Solr-exporter running with PID $PID"; fi
}

set_pid
status

case "$SERVICE_CMD" in 
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
esac
